// Code generated by Fabrica 0.4.7 (commit: 67e8b142ddff9e183446f588aa11f30741f9e933). DO NOT EDIT.
// Copyright © 2026 OpenCHAMI a Series of LF Projects, LLC
//
// SPDX-License-Identifier: MIT

package storage

//go:generate go run -mod=mod entgo.io/ent/cmd/ent generate ./ent/schema
