// Code generated by Fabrica 0.4.9 (commit: 70cad057c27c26728f9a12c01628afa5016b71cc). DO NOT EDIT.
// Copyright © 2026 OpenCHAMI a Series of LF Projects, LLC
//
// SPDX-License-Identifier: MIT

package storage

//go:generate go run -mod=mod entgo.io/ent/cmd/ent generate ./ent/schema
