// Code generated by Fabrica. DO NOT EDIT manually.
// SPDX-FileCopyrightText: Copyright © 2025-2026 OpenCHAMI a Series of LF Projects, LLC
// SPDX-License-Identifier: MIT
//
// This is a stub file created during init to prevent import errors.
// It will be replaced when you run 'fabrica generate --storage'

package storage

// Placeholder to prevent import errors - will be replaced by generated code
