// Code generated by Fabrica. DO NOT EDIT manually.
// SPDX-FileCopyrightText: Copyright © 2025-2026 OpenCHAMI a Series of LF Projects, LLC
// SPDX-License-Identifier: MIT
//
// This is a stub file created during init to prevent import errors.
// It will be replaced when Ent generates the real schema code.

package label

// Placeholder to prevent import errors - will be replaced by Ent-generated code
