// Code generated by Fabrica 0.4.7. DO NOT EDIT.
// Template: init/auth_helpers.go.tmpl
// Generated: 2026-06-04T14:34:11Z
//
// SPDX-FileCopyrightText: Copyright © 2026 OpenCHAMI a Series of LF Projects, LLC
//
// SPDX-License-Identifier: MIT

package main

import (
	"net/http"
)

func initializeAuthMiddleware(config *Config) (func(http.Handler) http.Handler, func(http.Handler) http.Handler, error) {

	return nil, nil, nil

}
