// Code generated by Fabrica 0.4.7. DO NOT EDIT.
// Template: init/metrics_helpers.go.tmpl
// Generated: 2026-06-04T14:34:11Z
//
// SPDX-FileCopyrightText: Copyright © 2026 OpenCHAMI a Series of LF Projects, LLC
//
// SPDX-License-Identifier: MIT

package main

func initializeMetricsServer(config *Config) {

}
